# Generated by Django 3.1.5 on 2021-02-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(
                    choices=[('moderation', 'на модерации'), ('published', 'опубликован'), ('rejected', 'отклонен')],
                    max_length=64)),
            ],
        ),
    ]
