# Generated by Django 3.1.5 on 2021-01-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210131_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(choices=[('moderation', 'на модерации'), ('published', 'опубликован'), ('rejected', 'отклонен')], max_length=64),
        ),
    ]
