# Generated by Django 3.1.5 on 2021-02-12 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('carts', '0002_cart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('delivery_dt', models.DateTimeField()),
                ('address', models.CharField(max_length=256)),
                ('status', models.CharField(
                    choices=[('created', 'создан'), ('delivered', 'доставлен'), ('processed', 'в процессе'),
                             ('cancelled', 'отменен')], default='created', max_length=64)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders',
                                           to='carts.cart')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders',
                                                to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
